services:
  ctm-cli:
    image: minhion/controlm-cli:24
    build:
      context: .
    environment:
      CTM_ENDPOINT: "${CTM_ENDPOINT}"
      CTM_API_TOKEN: "${CTM_API_TOKEN}"
      CTM_ENV_NAME: "${CTM_ENV_NAME:-default}"
    volumes:
      - ctm_backup:/opt/ctm/backup
      - ctm_capdef:/opt/ctm/capdef
      - ctm_dailylog:/opt/ctm/dailylog
      - ctm_data:/opt/ctm/data
      - ctm_measure:/opt/ctm/measure
      - ctm_onstmt:/opt/ctm/onstmt
      - ctm_pid:/opt/ctm/pid
      - ctm_procid:/opt/ctm/procid
      - ctm_sysout:/opt/ctm/sysout
      - ctm_status:/opt/ctm/status
      - ctm_temp:/opt/ctm/temp
      - ctm_cm:/opt/ctm/cm
      - ctm_se_storage:/home/controlm/se_storage
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ctm_backup:
  ctm_capdef:
  ctm_dailylog:
  ctm_data:
  ctm_measure:
  ctm_onstmt:
  ctm_pid:
  ctm_procid:
  ctm_sysout:
  ctm_status:
  ctm_temp:
  ctm_cm:
  ctm_se_storage:
